/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LiveListCheckResult = IDL.Record({
  'appName' : IDL.Text,
  'matchCount' : IDL.Nat,
  'matches' : IDL.Vec(IDL.Text),
});
export const LiveListCheckSummary = IDL.Record({
  'totalMatches' : IDL.Nat,
  'detailedResults' : IDL.Vec(LiveListCheckResult),
});
export const BulkCommentResult = IDL.Record({
  'usedCount' : IDL.Nat,
  'availableCount' : IDL.Nat,
  'comments' : IDL.Vec(IDL.Text),
});
export const ChatMessage = IDL.Record({
  'sender' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const RatingImage = IDL.Record({
  'imageBlob' : ExternalBlob,
  'uploaderName' : IDL.Text,
  'uploadTime' : IDL.Int,
});
export const BulkCommentTotals = IDL.Record({
  'totalLists' : IDL.Nat,
  'unusedComments' : IDL.Nat,
  'usedComments' : IDL.Nat,
  'totalComments' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Comment = IDL.Record({ 'text' : IDL.Text, 'used' : IDL.Bool });
export const CommentListSummary = IDL.Record({
  'name' : IDL.Text,
  'locked' : IDL.Bool,
  'usedComments' : IDL.Nat,
  'totalComments' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addLiveListApp' : IDL.Func([IDL.Text], [], []),
  'addSingleComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addUsernamesToApp' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUploadComments' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'checkLiveList' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [LiveListCheckSummary],
      ['query'],
    ),
  'clearAllCommentLists' : IDL.Func([], [], []),
  'createCommentList' : IDL.Func([IDL.Text], [], []),
  'deleteComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteList' : IDL.Func([IDL.Text], [], []),
  'deleteLiveListApp' : IDL.Func([IDL.Text], [], []),
  'deleteRatingImage' : IDL.Func([IDL.Nat], [], []),
  'generateBulkComments' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [BulkCommentResult],
      [],
    ),
  'generateSingleComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getAllChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getAllRatingImages' : IDL.Func([], [IDL.Vec(RatingImage)], ['query']),
  'getAvailableCommentLists' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAvailableLiveListApps' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getBulkCommentTotals' : IDL.Func([], [BulkCommentTotals], ['query']),
  'getBulkGeneratorKeyMasked' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentList' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(Comment))],
      ['query'],
    ),
  'getCommentListSummary' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CommentListSummary)],
      ['query'],
    ),
  'getListsWithLockStatus' : IDL.Func(
      [],
      [IDL.Vec(CommentListSummary)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasBulkGeneratorKey' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetAllLiveListApps' : IDL.Func([], [], []),
  'resetBulkGeneratorKey' : IDL.Func([], [], []),
  'resetList' : IDL.Func([IDL.Text], [], []),
  'resetUsernamesForApp' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBulkGeneratorKey' : IDL.Func([IDL.Text], [], []),
  'toggleLockList' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'uploadRatingImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LiveListCheckResult = IDL.Record({
    'appName' : IDL.Text,
    'matchCount' : IDL.Nat,
    'matches' : IDL.Vec(IDL.Text),
  });
  const LiveListCheckSummary = IDL.Record({
    'totalMatches' : IDL.Nat,
    'detailedResults' : IDL.Vec(LiveListCheckResult),
  });
  const BulkCommentResult = IDL.Record({
    'usedCount' : IDL.Nat,
    'availableCount' : IDL.Nat,
    'comments' : IDL.Vec(IDL.Text),
  });
  const ChatMessage = IDL.Record({
    'sender' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const RatingImage = IDL.Record({
    'imageBlob' : ExternalBlob,
    'uploaderName' : IDL.Text,
    'uploadTime' : IDL.Int,
  });
  const BulkCommentTotals = IDL.Record({
    'totalLists' : IDL.Nat,
    'unusedComments' : IDL.Nat,
    'usedComments' : IDL.Nat,
    'totalComments' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Comment = IDL.Record({ 'text' : IDL.Text, 'used' : IDL.Bool });
  const CommentListSummary = IDL.Record({
    'name' : IDL.Text,
    'locked' : IDL.Bool,
    'usedComments' : IDL.Nat,
    'totalComments' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addLiveListApp' : IDL.Func([IDL.Text], [], []),
    'addSingleComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addUsernamesToApp' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUploadComments' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'checkLiveList' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [LiveListCheckSummary],
        ['query'],
      ),
    'clearAllCommentLists' : IDL.Func([], [], []),
    'createCommentList' : IDL.Func([IDL.Text], [], []),
    'deleteComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteList' : IDL.Func([IDL.Text], [], []),
    'deleteLiveListApp' : IDL.Func([IDL.Text], [], []),
    'deleteRatingImage' : IDL.Func([IDL.Nat], [], []),
    'generateBulkComments' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [BulkCommentResult],
        [],
      ),
    'generateSingleComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getAllChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getAllRatingImages' : IDL.Func([], [IDL.Vec(RatingImage)], ['query']),
    'getAvailableCommentLists' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAvailableLiveListApps' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getBulkCommentTotals' : IDL.Func([], [BulkCommentTotals], ['query']),
    'getBulkGeneratorKeyMasked' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentList' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(Comment))],
        ['query'],
      ),
    'getCommentListSummary' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CommentListSummary)],
        ['query'],
      ),
    'getListsWithLockStatus' : IDL.Func(
        [],
        [IDL.Vec(CommentListSummary)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasBulkGeneratorKey' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetAllLiveListApps' : IDL.Func([], [], []),
    'resetBulkGeneratorKey' : IDL.Func([], [], []),
    'resetList' : IDL.Func([IDL.Text], [], []),
    'resetUsernamesForApp' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBulkGeneratorKey' : IDL.Func([IDL.Text], [], []),
    'toggleLockList' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'uploadRatingImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };