/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BulkCommentResult {
  'usedCount' : bigint,
  'availableCount' : bigint,
  'comments' : Array<string>,
}
export interface BulkCommentTotals {
  'totalLists' : bigint,
  'unusedComments' : bigint,
  'usedComments' : bigint,
  'totalComments' : bigint,
}
export interface ChatMessage {
  'sender' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Comment { 'text' : string, 'used' : boolean }
export interface CommentListSummary {
  'name' : string,
  'usedComments' : bigint,
  'totalComments' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface RatingImage {
  'imageBlob' : ExternalBlob,
  'uploaderName' : string,
  'uploadTime' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChatMessage' : ActorMethod<[string, string], undefined>,
  'addSingleComment' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUploadComments' : ActorMethod<[string, Array<string>], undefined>,
  'createCommentList' : ActorMethod<[string], undefined>,
  'deleteComment' : ActorMethod<[string, string], undefined>,
  'deleteList' : ActorMethod<[string], undefined>,
  'deleteRatingImage' : ActorMethod<[bigint], undefined>,
  'generateBulkComments' : ActorMethod<
    [string, bigint, string],
    BulkCommentResult
  >,
  'generateSingleComment' : ActorMethod<[string], string>,
  'getAllChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getAllRatingImages' : ActorMethod<[], Array<RatingImage>>,
  'getAvailableCommentLists' : ActorMethod<[], Array<string>>,
  'getBulkCommentTotals' : ActorMethod<[], BulkCommentTotals>,
  'getBulkGeneratorKeyMasked' : ActorMethod<[], [] | [string]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentList' : ActorMethod<[string], [] | [Array<Comment>]>,
  'getCommentListSummary' : ActorMethod<[string], [] | [CommentListSummary]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasBulkGeneratorKey' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resetBulkGeneratorKey' : ActorMethod<[], undefined>,
  'resetList' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBulkGeneratorKey' : ActorMethod<[string], undefined>,
  'uploadRatingImage' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];